#!/usr/bin/env bash

set -e

# If base revision was set, we are going to use given revision
# BASE_REVISION="db70372fd4ecbc111cb195ebe249809d8f0768a3" curl -sL https://...
BASE_REVISION="${BASE_REVISION:-main}"
BASE_URL="https://raw.githubusercontent.com/orochi-network/dev-off/${BASE_REVISION}"

DOCKER_FILE=()
DOCKER_COMMAND="[\"yarn\", \"start\"]"

while [[ $# -gt 0 ]]; do
  case $1 in
  -h | --help)
    echo "./dockerfile.sh [-t|--template] [-c|--command] [-f|--file]"
    exit 0
    ;;
  -t | --template)
    DOCKER_TEMPLATE="$2"
    shift # Past argument
    shift # Past value
    ;;
  -c | --command)
    DOCKER_COMMAND=${2:-${DOCKER_COMMAND}}
    shift
    shift
    ;;
  -f | --file)
    DOCKER_FILE+=("$2")
    shift
    shift
    ;;
  *)
    UNKNOWN_ARGS+=("$1") # Save unknown ones for later
    shift
    ;;
  esac
done

BUILD_PROD_SCRIPT="${BASE_URL}/scripts/build-prod-${DOCKER_TEMPLATE}.sh"
CONFIG_NGINX="${BASE_URL}/configs/nginx.conf"

CWD=$(pwd)
DF_BUFFER="${CWD}/Dockerfile"

check_file() {
  if [[ ! -f "$1" ]]; then
    echo "File $1 was not existed"
    exit 1
  fi
}

ubuntu_builder() {
  cat <<EOF >$DF_BUFFER
# This file was generated by using Orochi Network's DevOps Toolchains
# Please check: https://github.com/orochi-network/dev-off/
# Use our customized image based on Node.js and Ubuntu
FROM orochinetwork/ubuntu:node AS builder

# Mount NPM access token as secret
RUN --mount=type=secret,id=npm_access_token NPM_ACCESS_TOKEN=\$(cat /run/secrets/npm_access_token) && \\
  echo "//registry.npmjs.org/:_authToken=\$NPM_ACCESS_TOKEN" > /home/ubuntu/.npmrc && \\
  echo "enableTelemetry: 0\nnodeLinker: node-modules\nnpmScopes:" > /home/ubuntu/.yarnrc.yml && \\
  echo "  orochi-network:" >> /home/ubuntu/.yarnrc.yml && \\
  echo "    npmRegistryServer: \"https://registry.npmjs.org\"\n    npmAlwaysAuth: true" >> /home/ubuntu/.yarnrc.yml && \\
  echo "    npmAuthToken: \$NPM_ACCESS_TOKEN" >> /home/ubuntu/.yarnrc.yml && \\
  echo "  zkdb:" >> /home/ubuntu/.yarnrc.yml && \\
  echo "    npmRegistryServer: \"https://registry.npmjs.org\"\n    npmAlwaysAuth: true" >> /home/ubuntu/.yarnrc.yml && \\
  echo "    npmAuthToken: \$NPM_ACCESS_TOKEN" >> /home/ubuntu/.yarnrc.yml && \\
  mkdir -p /home/ubuntu/app && \\
  chown -R ubuntu:ubuntu /home/ubuntu

# Set the working directory
WORKDIR /home/ubuntu/app

# Copy the application code as the non-root user
COPY --chown=ubuntu:ubuntu . .

# Switch to non-root ubuntu:ubuntu
USER ubuntu:ubuntu
EOF

  if [[ -f "$CWD/scripts/build-prod.sh" ]]; then
    echo "Using local build-prod.sh"
    cat <<EOF >>$DF_BUFFER

# Run build-prod.sh
RUN chmod +x scripts/build-prod.sh && \\
  ./scripts/build-prod.sh
EOF
  else
    echo "Using remote build script"
    cat <<EOF >>$DF_BUFFER

# Run default build script
RUN curl -sL $BUILD_PROD_SCRIPT | bash -eo pipefail
EOF
  fi
}

alpine_nginx() {
  if [[ -f "${CWD}/nginx.conf" ]]; then
    echo "Using local ./nginx.conf"
    cat <<EOF >>$DF_BUFFER

# Use stable nginx on alpine
FROM nginx:stable-alpine AS runner

# Chown cache and pid to nginx:nginx
RUN chown -R nginx:nginx /var/cache/nginx && \\
  touch /run/nginx.pid && \\
  chown -R nginx:nginx /run/nginx.pid

WORKDIR /usr/share/nginx/html

# Copy production & nginx config
COPY --from=builder --chown=nginx:nginx /home/ubuntu/app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder --chown=nginx:nginx /home/ubuntu/app/build /usr/share/nginx/html/

# Change default user to ngin:nginx
USER nginx:nginx

# Expose http port 80
EXPOSE 80
EOF
  else
    echo "Using remote nginx.conf"
    cat <<EOF >>$DF_BUFFER

# Use stable nginx on alpine
FROM nginx:stable-alpine AS runner

# Chown cache and pid to nginx:nginx
RUN chown -R nginx:nginx /var/cache/nginx && \\
  touch /run/nginx.pid && \\
  chown -R nginx:nginx /run/nginx.pid && \\
  curl -o /etc/nginx/conf.d/default.conf ${CONFIG_NGINX} && \\
  chown nginx:nginx /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

# Copy production & nginx config
COPY --from=builder --chown=nginx:nginx /home/ubuntu/app/build /usr/share/nginx/html/

# Change default user to ngin:nginx
USER nginx:nginx

# Expose http port 80
EXPOSE 80
EOF
  fi
}

alpine_node() {
  check_file $CWD/package.json
  cat <<EOF >>$DF_BUFFER

# Use stable node on alpine
FROM node:24-alpine AS runner

# Make app folder for application
RUN mkdir -p /home/node/app && \\
  chown -R node:node /home/node && \\
  chmod -R 750 /home/node/app

# Set default working dir 
WORKDIR /home/node/app
EOF

  for item in "${DOCKER_FILE[@]}"; do
    echo "Copy file: ${item}"
    echo "COPY --from=builder --chown=node:node /home/ubuntu/app/${item} ./${item}" >>$DF_BUFFER
  done

  cat <<EOF >>$DF_BUFFER

# Switch to node:node user
USER node:node

# Execute command
CMD ${DOCKER_COMMAND}
EOF
}

alpine_next() {
  check_file $CWD/package.json
  cat <<EOF >>$DF_BUFFER

# Use stable nginx on alpine
FROM node:24-alpine AS runner

ENV NEXT_TELEMETRY_DISABLED=1

# Make app folder for application
RUN mkdir -p /home/node/app && \\
  chown -R node:node /home/node && \\
  chmod -R 750 /home/node/app

# Set default working dir 
WORKDIR /home/node/app
EOF

  for item in "${DOCKER_FILE[@]}"; do
    echo "Copy file: ${item}"
    echo "COPY --from=builder --chown=node:node /home/ubuntu/app/${item} ./${item}" >>$DF_BUFFER
  done

  cat <<EOF >>$DF_BUFFER

# Switch to node:node user
USER node:node

# Execute command
CMD ${DOCKER_COMMAND}
EOF
}

echo "Generating Dockerfile using template: ${DOCKER_TEMPLATE}"
case $DOCKER_TEMPLATE in
node)
  echo "Using @orochi-network/ubuntu:node builder"
  ubuntu_builder
  echo "Using node:24-alpine runner"
  alpine_node
  ;;
nginx)
  echo "Using @orochi-network/ubuntu:node builder"
  ubuntu_builder
  echo "Using nginx:stable-alpine runner"
  alpine_nginx
  ;;
next)
  echo "Using @orochi-network/ubuntu:node builder"
  ubuntu_builder
  echo "Using node:24-alpine runner"
  alpine_next
  ;;
rust) ;;
esac
