#!/usr/bin/env bash

set -e

DOCKER_FILE=()
DOCKER_COMMAND="[\"yarn\", \"start\"]"

while [[ $# -gt 0 ]]; do
  case $1 in
  -h | --help)
    echo "./dockerfile.sh [-t|--template] [-c|--command] [-f|--file]"
    exit 0
    ;;
  -t | --template)
    DOCKER_TEMPLATE="$2"
    shift # Past argument
    shift # Past value
    ;;
  -c | --command)
    DOCKER_COMMAND=${2:-${DOCKER_COMMAND}}
    shift
    shift
    ;;
  -f | --file)
    DOCKER_FILE+=("$2")
    shift
    shift
    ;;
  *)
    UNKNOWN_ARGS+=("$1") # Save unknown ones for later
    shift
    ;;
  esac
done

CWD=$(pwd)
DF_BUFFER="${CWD}/Dockerfile"

check_file() {
  if [[ ! -f "$1" ]]; then
    echo "File $1 was not existed"
    exit 1
  fi
}

ubuntu_builder() {
  check_file $CWD/scripts/build-prod.sh
  cat <<EOF >$DF_BUFFER
# This file was generated by using Orochi Network's DevOps Toolchains
# Please check: https://github.com/orochi-network/dev-off/
# Use our customized image based on Node.js and Ubuntu
FROM orochinetwork/ubuntu:node AS builder

# Mount NPM access token as secret
RUN --mount=type=secret,id=npm_access_token NPM_ACCESS_TOKEN=\$(cat /run/secrets/npm_access_token) && \\
  echo "//registry.npmjs.org/:_authToken=\$NPM_ACCESS_TOKEN" > /home/ubuntu/.npmrc && \\
  echo "enableTelemetry: 0\nnodeLinker: node-modules\nnpmScopes:" >> /home/ubuntu/.yarnrc.yml && \\
  echo "  orochi-network:" > /home/ubuntu/.yarnrc.yml && \\
  echo "    npmRegistryServer: \"https://registry.npmjs.org\"\n    npmAlwaysAuth: true" >> /home/ubuntu/.yarnrc.yml && \\
  echo "    npmAuthToken: \$NPM_ACCESS_TOKEN" >> /home/ubuntu/.yarnrc.yml && \\
  echo "  zkdb:" > /home/ubuntu/.yarnrc.yml && \\
  echo "    npmRegistryServer: \"https://registry.npmjs.org\"\n    npmAlwaysAuth: true" >> /home/ubuntu/.yarnrc.yml && \\
  echo "    npmAuthToken: \$NPM_ACCESS_TOKEN" >> /home/ubuntu/.yarnrc.yml && \\
  mkdir -p /home/ubuntu/app && \\
  chown -R ubuntu:ubuntu /home/ubuntu

# Set the working directory
WORKDIR /home/ubuntu/app

# Copy the application code as the non-root user
COPY --chown=ubuntu:ubuntu . .

# Switch to non-root ubuntu:ubuntu
USER ubuntu:ubuntu

# Run the complete build-prod process (git version injection + yarn build)
RUN chmod +x scripts/build-prod.sh && ./scripts/build-prod.sh
EOF
}

alpine_nginx() {
  check_file $CWD/nginx.conf
  cat <<EOF >>$DF_BUFFER

# Use stable nginx on alpine
FROM nginx:stable-alpine AS runner

# Chown cache and pid to nginx:nginx
RUN chown -R nginx:nginx /var/cache/nginx && \\
  touch /run/nginx.pid && \\
  chown -R nginx:nginx /run/nginx.pid

WORKDIR /usr/share/nginx/html

# Copy production & nginx config
COPY --from=builder --chown=nginx:nginx /home/ubuntu/app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder --chown=nginx:nginx /home/ubuntu/app/build /usr/share/nginx/html/

# Change default user to ngin:nginx
USER nginx:nginx

# Expose http port 80
EXPOSE 80
EOF
}

alpine_node() {
  check_file $CWD/package.json
  cat <<EOF >>$DF_BUFFER

# Use stable nginx on alpine
FROM node:24-alpine AS runner

# Make app folder for application
RUN mkdir -p /home/node/app && \
  chown -R node:node /home/node && \
  chmod -R 750 /home/node/app

# Set default working dir 
WORKDIR /home/node/app
EOF

  for item in "${DOCKER_FILE[@]}"; do
    echo "COPY --from=builder --chown=node:node /home/ubuntu/app/${item} ./${item}" >>$DF_BUFFER
  done

  cat <<EOF >>$DF_BUFFER

# Switch to node:node user
USER node:node

# Execute command
CMD ${DOCKER_COMMAND}
EOF
}

case $DOCKER_TEMPLATE in
node)
  echo "Using @orochi-network/ubuntu:node builder"
  ubuntu_builder
  echo "Using node:24-alpine runner"
  alpine_node
  ;;
nginx)
  echo "Using @orochi-network/ubuntu:node builder"
  ubuntu_builder
  echo "Using nginx:stable-alpine runner"
  alpine_nginx
  ;;
rust) ;;
esac
