#!/usr/bin/env bash

# Generates ssh-allowed-signers from GitHub SSH public keys.
# Run locally and commit the result. Mirrors the gpg/ folder membership.
# Usage: ./generate-ssh-allowed-signers.sh

set -euo pipefail

# GitHub usernames — mirrors the gpg/ folder (one entry per *.asc file)
GITHUB_USERS=(
  alothanhh
  BaoNinh2808
  brianw3b
  CaoHoaiTan
  chiro-hiro
  Github
  harris1111
  hungnguyen18
  ngotrongphuc
  nguyendinhthang3101
  SangTran-127
  ThanhNguyen03
)

OUTPUT="ssh-allowed-signers"
CHECKSUM_FILE="checksum.sha256"

# Write header
cat > "$OUTPUT" <<'EOF'
# SSH Allowed Signers for Orochi Network
# Format: <principal> <key-type> <key-data>
# Generated by generate-ssh-allowed-signers.sh — do not edit manually.
# Accepted key types: ssh-ed25519, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, ssh-rsa
# Principal "*" matches any committer email; key fingerprint is the enforcement layer.
EOF

# Fetch and append SSH keys for each user
for USER in "${GITHUB_USERS[@]}"; do
  KEYS=$(curl -fsSL "https://github.com/${USER}.keys" 2>/dev/null || true)

  if [[ -z "$KEYS" ]]; then
    echo "WARNING: no SSH keys found for $USER — skipping"
    continue
  fi

  echo "" >> "$OUTPUT"
  echo "# $USER" >> "$OUTPUT"

  while IFS= read -r KEY; do
    [[ -z "$KEY" ]] && continue
    echo "* $KEY" >> "$OUTPUT"
  done <<< "$KEYS"

  KEY_COUNT=$(echo "$KEYS" | grep -c '.' || true)
  echo "  $USER: $KEY_COUNT key(s) added"
done

# Update checksum.sha256 — replace existing entry or append
NEW_HASH=$(sha256sum "./$OUTPUT" | awk '{print $1}')
ENTRY="${NEW_HASH}  ./${OUTPUT}"

if grep -q "\./${OUTPUT}" "$CHECKSUM_FILE" 2>/dev/null; then
  # Replace existing line
  sed -i.bak "s|.*\./${OUTPUT}|${ENTRY}|" "$CHECKSUM_FILE" && rm -f "${CHECKSUM_FILE}.bak"
else
  echo "$ENTRY" >> "$CHECKSUM_FILE"
fi

echo ""
echo "Done: $OUTPUT updated and checksum written to $CHECKSUM_FILE"
