#!/usr/bin/env bash

# Generates ssh-allowed-signers from GitHub SSH public keys.
# Run locally and commit the result.
# Usage: ./generate-ssh-allowed-signers.sh

set -euo pipefail

cd "$(dirname "$0")"

# GitHub usernames authorized to sign commits via SSH. This is a SECURITY
# BOUNDARY: every key fetched here becomes a trusted signer. Add/remove entries
# deliberately and review in a signed PR. See SECURITY.md for the onboarding flow.
GITHUB_USERS=(
  brng1151
  chiro-hiro
  bao-ninh-orochi
  chirojr
)

OUTPUT="ssh-allowed-signers"

# Write header
cat > "$OUTPUT" <<'EOF'
# SSH Allowed Signers for Orochi Network
# Format: <principal> <key-type> <key-data>
# Generated by generate-ssh-allowed-signers.sh — do not edit manually.
# Accepted key types: ssh-ed25519, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, ssh-rsa
# Principal "*" matches any committer email; key fingerprint is the enforcement layer.
EOF

# Fetch and append SSH keys for each user
for USER in "${GITHUB_USERS[@]}"; do
  KEYS=$(curl -fsSL --connect-timeout 15 --max-time 120 --retry 3 --retry-delay 2 "https://github.com/${USER}.keys" 2>/dev/null || true)

  if [[ -z "$KEYS" ]]; then
    echo "WARNING: no SSH keys found for $USER — skipping"
    continue
  fi

  echo "" >> "$OUTPUT"
  echo "# $USER" >> "$OUTPUT"

  while IFS= read -r KEY; do
    [[ -z "$KEY" ]] && continue
    echo "* $KEY" >> "$OUTPUT"
  done <<< "$KEYS"

  KEY_COUNT=$(echo "$KEYS" | grep -c '.' || true)
  echo "  $USER: $KEY_COUNT key(s) added"
done

# Refresh checksums via the single source of truth.
echo ""
./generate-checksums.sh

echo ""
echo "Done: $OUTPUT updated and checksum.sha256 refreshed"
